CREATE TABLE IF NOT EXISTS notifications (
     id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
     user_id BIGINT NOT NULL,
     title VARCHAR(255) NOT NULL,
     message TEXT,
     read BOOLEAN DEFAULT FALSE,
     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

CONSTRAINT fk_notification_user
    FOREIGN KEY (user_id)
     REFERENCES users(id)
     ON DELETE CASCADE
);
