CREATE TABLE IF NOT EXISTS users (
     id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY UNIQUE,
     login VARCHAR(100) NOT NULL UNIQUE,
     password VARCHAR(128) NOT NULL,
     first_name VARCHAR(100) NOT NULL,
     last_name VARCHAR(100) NOT NULL,
     email VARCHAR(64) UNIQUE,
     phone VARCHAR(32),
     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     banned BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS events (
     id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY UNIQUE,
     title VARCHAR(200) NOT NULL,
     description VARCHAR(4048),
     event_datetime TIMESTAMP NOT NULL,
     location VARCHAR(255),
     category VARCHAR(255),
     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS event_users (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    user_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    role VARCHAR(20) NOT NULL CHECK (role IN ('ORGANIZER', 'PARTICIPANT')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_event_user_user
    FOREIGN KEY (user_id)
    REFERENCES users(id) ON DELETE CASCADE,

    CONSTRAINT fk_event_user_event
    FOREIGN KEY (event_id)
    REFERENCES events(id) ON DELETE CASCADE,

    CONSTRAINT uq_event_user_role
    UNIQUE (event_id, user_id)
);